### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by teachtyler** [TransitFeeds/TransitFeeds-Public#105]
I'm getting 'Access-Control-Allow-Origin' error on localhost:9000 is there a specific port I need to use for the API? 
`
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.
`

**Comment by HendX** [comment]
Hmm - exactly how are you attempting to use the API?

**Comment by teachtyler** [comment]
I have an angular, my factory for the requests are here in my transit-app repo:
[transitFactory.js](https://github.com/teachtyler/Transit-App/blob/master/app/services/transitFactory.js)
I want to view it as a single page app later with offline-first functionality.

**Comment by HendX** [comment]
I believe I just need to add the following header to my API responses:

Access-Control-Allow-Origin: *

I'm undecided as to whether this is a good idea or not. Open to your feedback on this.

**Comment by teachtyler** [comment]
You're going to love this, I was looking up to see how safe it'd be to allow all origins,  I randomly found this [chrome app](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en) and now I'm successfully getting my requests through.  

I'd say it's safe to add this, since a tool can replicate it, however I would make double sure, and for GET method only?

**Comment by HendX** [comment]
Thanks for the info - the API is read-only (at this time, anyway), so I agree that it's most likely safe. I'm going to not put it in for now however, but I'll leave this issue open.

**Comment by rszczypka** [comment]
Hi @HendX ,
I'm working on a single page app build in React+Redux and going to use your API to check if there is a new update to GTFS feed and download it if so.

Because I'm calling the API from the browser I'm also getting the Access-Control-Allow-Origin error.

Could you please add `Access-Control-Allow-Origin: *`. Use the Access-Control-Allow-Origin header only on chosen URLs that need to be accessed cross-domain. Don't use the header for the whole domain.

Because your API is read-only there's no security issues to add this feature.
You can also limit the possible request methods by setting:
`Access-Control-Allow-Methods: GET`

**Comment by HendX** [comment]
Thanks @rszczypka & @teachtyler 

I've now added the following to API responses:

Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET

I don't anticipate any problems doing so, but if so, I may roll it back and possible just enable it on an account-by-account basis.
