### ISSUE TITLE
METRO Houston GTFS page isn't updating

### ISSUE THREAD

**Issue by colinmcglynn** [TransitFeeds/TransitFeeds-Public#142]
The METRO Houston GTFS http://transitfeeds.com/p/metro/25 page isn't updating with the latest GTFS for the agency, even though the Offical Download Link included on the page is correct and has the latest GTFS.

(This is a repeat of this issue https://github.com/TransitFeeds/TransitFeeds-Public/issues/102, but I don't have the permissions to reopen the original)

**Comment by HendX** [comment]
Thanks again. It appears the issue is that their web server returns 304 Not Modified when I pass any value in for If-Modified-Since, rather than a 200.

So even though I say "If-Modified-Since March 21 2016", it says 304. If I don't include this, it returns 200 and their modified date of May 2016.

```
$ curl -vvvv -X GET http://www.ridemetro.org/Downloads/google_transit.zip -z "Tue, 22 Mar 2016 04:45:01 GMT"

> GET /Downloads/google_transit.zip HTTP/1.1
> Host: www.ridemetro.org
> User-Agent: curl/7.43.0
> Accept: */*
> If-Modified-Since: Tue, 22 Mar 2016 04:45:01 GMT
> Cache-Control: max-age=0
> If-None-Match: 123
> 
< HTTP/1.1 304 NOT MODIFIED
```

Here's without the If-Modified-Since:

```
$ curl -vvvv -X GET http://www.ridemetro.org/Downloads/google_transit.zip

* Connected to www.ridemetro.org (206.225.177.63) port 80 (#0)
> GET /Downloads/google_transit.zip HTTP/1.1
> Host: www.ridemetro.org
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: private,max-age=0
< Content-Length: 11350151
< Content-Type: application/x-zip-compressed
< Expires: Tue, 17 May 2016 04:43:08 GMT
< Last-Modified: Thu, 12 May 2016 20:36:02 GMT
```

Interestingly enough, specifying a HEAD request instead returns the correct result, however the system isn't setup to first perform a HEAD request then a GET (it could though, I'm just worried about the impact on other feeds).

**Comment by HendX** [comment]
My solution in the short term is to keep sending the If-Modified-Since header as previously, however if that date is more than 2 weeks old, not going to send it.

This means a lot of extraneous data will be downloaded for infrequently updated feeds, but at least this feed (and a handful of others this is happening to) will update (eventually...).

Unless I can figure out how this is happening, the solution of performing a HEAD first might be the way to go, or alternatively, performing additional smarts to flag certain feeds as "trouble" feeds that need a full request with the If-Modified-Since.
