### ISSUE TITLE
Málaga (spain) GFTS

### ISSUE THREAD

**Issue by ciudadrealbus** [TransitFeeds/TransitFeeds-Public#152]
Find attached the link for the city bus network called EMT Málaga. (Málaga's Municipal Transport Company)

http://datosabiertos.malaga.eu/recursos/transporte/EMT/lineasYHorarios/google_transit.zip

**Comment by mldickens** [comment]
http://datosabiertos.malaga.eu/dataset/lineas-y-horarios-bus-google-transit

I am hesitant to add this since it contains a bunch of CSV files (not text files) and it excludes some required files like agency.txt

**Comment by HendX** [comment]
Agreed @mldickens - even though the CSV files look to be to spec, they won't import correctly since the spec also states they must be *.txt files.

@ciudadrealbus - if you're the admin for the feed, could you update it to be to spec (which as @mldickens points out, should also contain `agency.txt`).
