### ISSUE TITLE
GTFS-realtime as JSON

### ISSUE THREAD

**Issue by araichev** [TransitFeeds/TransitFeeds-Public#158]
Hi there,

Is there a way to download from TransitFeeds GTFS-realtime feeds in JSON format instead of in protobuf text format?

**Comment by RideSchedules** [comment]
How did you get the protobuf format without the official URL?

**Comment by HendX** [comment]
@araichev - it's possible but since TransitFeeds isn't continually updating the feed it won't serve a great use. Note that it's possible to view the "raw" protobuf data.

@RideSchedules - this is generally the case when a third-party agreement has been required or there is a username/password required. In that case I try to include access info so you can get access yourself. Which feed are you referring to?

**Comment by sanbeg** [comment]
How often do the realtime feeds get updated?  Whenever I've checked, the one I've been looking at is about a half hour old.  That should be recent enough to get alerts, which I don't have another source for.  Of course a JSON version would be much easier.

**Comment by HendX** [comment]
Hi @sanbeg - we deliberately only update them hourly, and don't include them in the API in order to prevent users from sourcing the data from us. Our servers don't have the capacity for this.

You'll will need your own method for accessing and processing the protobuf from the source web site. There are many tools available for converting pb into JSON.
