### ISSUE TITLE
Transit Feed for NSW is excluding buses

### ISSUE THREAD

**Issue by manishkumar1618** [TransitFeeds/TransitFeeds-Public#19]
This feed is downloaded 
https://tdx.transportnsw.info/download/files/greater_sydney_gtfs_static.zip

instead of:
https://tdx.transportnsw.info/download/files/full_greater_sydney_gtfs_static.zip

**Comment by eveleighpc** [comment]
update:
Consolidation of GTFS files on the NSW Transport Data Exchange Program
Commencing 15 May 2015, the NSW Transport Data Exchange Program will no longer host the "State Transit (Sydney Buses)" and "Greater Sydney (excluding State Transit)" GTFS files.

Rather than host 3 separate files with a large amount of duplicated data, only one GTFS file will be hosted - the currently available "ALL Greater Sydney" GTFS, which contains rail, ferry, light rail and bus data, including State Transit.

Any subscribers regularly using the "State Transit (Sydney Buses)" or "Greater Sydney (excluding State Transit)" files are advised to switch to the "ALL Greater Sydney" GTFS file prior to 15 May.

If you have any queries regarding the Transport Data Exchange program please contact TDX@transport.nsw.gov.au.

Regards,
TDX Team
Transport for NSW

**Comment by HendX** [comment]
Thanks, this has been updated now. You can verify the Sydney Buses routes are here:

http://transitfeeds.com/p/transport-for-nsw/237/latest/routes?agency=11954
