### ISSUE TITLE
Update VBB region feed for 2015 data

### ISSUE THREAD

**Issue by jugalps** [TransitFeeds/TransitFeeds-Public#20]
TransitFeed still uses 2013 data for [VBB region](http://transitfeeds.com/p/verkehrsverbund-berlin-brandenburg/213). It would be good to update it for [2015 data](http://images.vbb.de/assets/ftp/file/36600.zip) as well. 

Additionally, is there a way for the user to upload it manually or atleast provide a link for the new dataset?

**Comment by jhermsmeier** [comment]
Just as an FYI;
Another source of 2015 data: [vbb-fahrplandaten-april-2015-bis-dezember-2015](http://daten.berlin.de/datensaetze/vbb-fahrplandaten-april-2015-bis-dezember-2015)
More GTFS data from Berlin Open Data: http://daten.berlin.de/search/node/gtfs

**Comment by HendX** [comment]
Thanks for the update @jhermsmeier. Sorry @jugalps, I completely missed this issue.

Ideally there will be a static URL that can be used even when the data is updated. Next best is a static URL that links to the latest file, because I can scrape the URL from that at least.

I've updated it manually for the current feed, but it'll likely need to be updated again after December.

**Comment by HendX** [comment]
Data is now updated here: http://transitfeeds.com/p/verkehrsverbund-berlin-brandenburg/213

**Comment by HendX** [comment]
Oh and to answer your question @jugalps, at this time the best way to submit an updated URL is to create an issue here on GitHub. I'll try not to miss it in future :)
