### ISSUE TITLE
Netherlands feed

### ISSUE THREAD

**Issue by joriswu** [TransitFeeds/TransitFeeds-Public#58]
In Netherlands, www.ovapi.nl aggegrates feeds from multiple agencies into a set that covers the country.

**Comment by HendX** [comment]
Thanks - we had this on the site previously, but the amount of data required to process causes issues for our server. I will leave this job open for now until I can figure a compromise that will still allow it to be listed on the site.

**Comment by joriswu** [comment]
Main reason is that the OVapi feed does not use the calendar.txt file, yet provides a half year period using calendar_dates.txt. That makes all trips enumerated per day.

**Comment by skinkie** [comment]
If you profile the data processing. What is the part that takes the most amount of time?

**Comment by HendX** [comment]
I think it's basically the size of the feed, offset with the frequency it is updated. If it was updated say monthly then all would be fine, but it's more like daily.

I need to reengineer the site to process feeds independently of the web server so it can scale as required.

**Comment by skinkie** [comment]
What if we would contribute a feed that is compressed, hence tripids are stable, maybe even going for frequencies.txt, but can't be related to GTFS-RT updates (easily). Would that help?

**Comment by HendX** [comment]
I think this may help - but the biggest issue is likely the frequency with which it updates.

TransitFeeds should really have the option to set the frequency with which is checks feeds, but I haven't settled on the best way to attack this, since it may cause the site to miss "big updates" (e.g. if it checks only weekly but checks the day before a big update, then that'd be 6 days with the wrong data)

**Comment by HendX** [comment]
I've made various improvements to the processing and re-added the feeds here:

https://transitfeeds.com/p/ov

Still importing at time of writing.
